import { DEFAULT_FILES } from '../constants/default-files';
import { getWebContainerFiles } from './file-parser';

/**
 * Export project files as a downloadable ZIP archive.
 */
export async function exportToZip(
  files: Record<string, string>,
  projectName: string = 'stitch-project'
): Promise<void> {
  const { default: JSZip } = await import('jszip');
  const zip = new JSZip();
  const webContainerFiles = getWebContainerFiles(files);
  const allFiles = { ...DEFAULT_FILES, ...webContainerFiles };

  Object.entries(allFiles).forEach(([path, content]) => {
    if (path === 'public/index.html') return;
    zip.file(path, content);
  });

  if (!files['index.html']) {
    zip.file(
      'index.html',
      `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React + TS + Tailwind</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>`
    );
  }

  if (!files['package.json']) {
    zip.file(
      'package.json',
      JSON.stringify(
        {
          name: 'stitch-generated-app',
          private: true,
          version: '0.0.0',
          type: 'module',
          scripts: { dev: 'vite', build: 'tsc && vite build', preview: 'vite preview' },
          dependencies: {
            react: '^18.2.0',
            'react-dom': '^18.2.0',
            'react-router-dom': '^6.22.3',
            'lucide-react': '^0.344.0',
            'framer-motion': '^11.0.8',
            clsx: '^2.1.0',
            'tailwind-merge': '^2.2.1',
          },
          devDependencies: {
            '@types/react': '^18.2.66',
            '@types/react-dom': '^18.2.22',
            '@vitejs/plugin-react': '^4.2.1',
            tailwindcss: '^3.4.1',
            postcss: '^8.4.35',
            autoprefixer: '^10.4.18',
            typescript: '^5.2.2',
            vite: '^5.2.0',
          },
        },
        null,
        2
      )
    );
  }

  if (!files['vite.config.ts']) {
    zip.file(
      'vite.config.ts',
      `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`
    );
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Open the project in StackBlitz in a new window.
 */
export async function exportToStackBlitz(
  files: Record<string, string>,
  projectName: string
): Promise<void> {
  const { default: sdk } = await import('@stackblitz/sdk');
  const webContainerFiles = getWebContainerFiles(files);
  sdk.openProject(
    {
      title: projectName,
      description: 'Generated by Statch AI Engine',
      template: 'node',
      files: webContainerFiles,
      settings: {
        compile: { trigger: 'auto', clearConsole: false },
      },
    },
    { newWindow: true }
  );
}
